### ISSUE TITLE
编译的时候出错

### ISSUE THREAD

**Issue by handsome2456** [chengwei0427/simple_gnss_localizer#2]
CMake Error at simple_gnss_localizer/third_party/GeographicLib/CMakeLists.txt:34 (add_library):
  add_library cannot create target "libGeographiccc" because another target
  with the same name already exists.  The existing target is a shared library
  created in source directory
  "/home/lz/catkin_ws/src/imu_gps_localization-master/imu_gps_localizer/third_party/GeographicLib".
  See documentation for policy CMP0002 for more details.

**Comment by chengwei0427** [comment]
Sorry for later reply. 
There is a same name "GeographicLib" , you  can check here.
