### ISSUE TITLE
加载不出来地图

### ISSUE THREAD

**Issue by xionghuachuan** [chengwei0427/simple_gnss_localizer#3]
Unable to decode image at http://a.tiles.mapbox.com/v4/mapbox.satellite/18/208674/108582.jpg?access_token=pk.eyJ1IjoidGgzY29yeWQiLCJhIjoiY2l5MjNramozMDAxYTMybnR4Y296NmZ6bCJ9.Qx4UJrlAlu5kK1GvrCvmig
显示这个Error，不知道怎么解决？

**Comment by chengwei0427** [comment]
跟网络有关，有时候确实不能加载，我也遇到了；
或者你看看能否翻墙

**Comment by xionghuachuan** [comment]
> 

感谢回复！
现在把梯子挂着，但还是出不了图！

**Comment by xionghuachuan** [comment]
> 跟网络有关，有时候确实不能加载，我也遇到了； 或者你看看能否翻墙
是需要一直等着它加载吗？

**Comment by chengwei0427** [comment]
一般加载完成后，你的rviz_satellite/mapscache文件夹中会有很多的文件，里面就是缓冲的地图；

我之前也是加载不出来某个区块的地图，但是我另外一台电脑，就可以加载，最后我是把另外一台加载的地方，拷贝过来，才能适用的。

你可以先等着他加载一段时间，因为下载地图，可能也需要时间的。

多试几次吧；

**Comment by chengwei0427** [comment]
还有，你设置的不同视野高度，加载的地图大小也不同，需要下载完成才能显示的。

**Comment by xionghuachuan** [comment]
> 一般加载完成后，你的rviz_satellite/mapscache文件夹中会有很多的文件，里面就是缓冲的地图；
> 
> 我之前也是加载不出来某个区块的地图，但是我另外一台电脑，就可以加载，最后我是把另外一台加载的地方，拷贝过来，才能适用的。
> 
> 你可以先等着他加载一段时间，因为下载地图，可能也需要时间的。
> 
> 多试几次吧；

好的好的，感谢！！每次都给你一键三连！向你学习，respect！

**Comment by Zdctryto** [comment]
> > 一般加载完成后，你的rviz_satellite/mapscache文件夹中会有很多的文件，里面就是缓冲的地图；
> > 我之前也是加载不出来某个区块的地图，但是我另外一台电脑，就可以加载，最后我是把另外一台加载的地方，拷贝过来，才能适用的。
> > 你可以先等着他加载一段时间，因为下载地图，可能也需要时间的。
> > 多试几次吧；
> 
> 好的好的，感谢！！每次都给你一键三连！向你学习，respect！
这个问题你解决了没，我也出现这样的错误了
